version: "3.9"

services:
  rabbitmq-yarrow:
    image: rabbitmq:3-management-alpine
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq_yarrow
    environment:
      RABBITMQ_DEFAULT_USER: "username"
      RABBITMQ_DEFAULT_PASS: "password"
#    container_name: "rabbitmq"

  yarrow:
    build:
      context: .
      dockerfile: Dockerfile
      target: yarrow
    environment:
      HOST: rabbitmq-yarrow
      PORT: 5672
      VIRTUAL_HOST: /
      USERNAME: username
      PASSWORD: password
      MODULE_NAME: example.example
    volumes:
      - ./yarrow:/tmp/yarrow/yarrow
    depends_on:
      - rabbitmq-yarrow

#  integration-tests:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: pytest
#    depends_on:
#      - yarrow
#    environment:
#      RABBITMQ_VIRTUAL_HOST: abc
#      RABBITMQ_HOST: rabbitmq
#      RABBITMQ_PORT: 5672
#      RABBITMQ_USERNAME: username
#      RABBITMQ_PASSWORD: password
#
#    volumes:
#      - integration_tests:/app


volumes:
  rabbitmq_data: {}
